version: '3.8'

services:
  db:
    container_name: postgres
    image: postgres:14.5-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: 'test_db'
    env_file:
      - ./.env
    ports:
      - 5432:5432

  web:
    container_name: web
    build:
      target: django
    depends_on:
      - db
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    environment:
      POSTGRES_DB: 'test_db'
    env_file:
      - ./.env


volumes:
  db_data: